### ISSUE TITLE
Jdeps error: "Module virtualizedfx not found, required by MaterialFX"

### ISSUE THREAD

**Issue by AntoninHuaut** [palexdev/MaterialFX#152]
Hi,
I'm currently trying to upgrade my project from JFoenix to MaterialFX but I'm having an error with JDeps (used by [JavaPackager](https://github.com/fvarrui/JavaPackager)).  

```
[INFO]     Bundling JRE ... with C:\Program Files\Java\jdk-17.0.2
[INFO]         Creating customized JRE ...
[INFO]         Getting required modules ... 
[INFO]             Executing command: cmd.exe /s /c ""C:\Program Files\Java\jdk-17.0.2\bin\jdeps" -q --multi-release 17 --ignore-missing-deps --print-module-deps C:\Users\XXX\Documents\Projets\XXX\XXX-fx\target\XXX\libs\*.jar C:\Users\XXX\Documents\Projets\XXX\XXX-fx\target\XXX_1.4.0-SNAPSHOT-lite.jar"
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module virtualizedfx not found, required by MaterialFX
[ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```

The module virtualizedfx is not found and is required by MaterialFX. I try to add it in maven, my module-info but I'm still getting this error.  

I see this [issue](https://github.com/palexdev/MaterialFX/issues/41#issuecomment-921679664) and you called it a error normale, but it is quite problematic for me.

VirtualizedFX must be a modular project :/

**Comment by palexdev** [comment]
@AntoninHuaut should be fixed in latest release
