### ISSUE TITLE
Can't see the symbols

### ISSUE THREAD

**Issue by liraneliav** [palexdev/MaterialFX#209]
Hello Palexdev team,
We are trying to use your API for MaterialFX in our project. Somehow, we got into issue such that when we are using your components, the icons that are used with the component we are using are not appearing. 
(Adding a photo to express better the issue). We will happy to understand how we can fix that and keep on using your API.
Thanks in advance and keep up woth yuor good job!!
Hopeless students 
![screenshot](https://user-images.githubusercontent.com/102174057/170697136-60fce2c6-4342-4460-9f4f-37ed6346b372.JPG)

**Comment by goatfanboi23** [comment]
Having same issue, I saw this was closed, how did you resolve it

**Comment by stefanofornari** [comment]
Icons in MFX have a bit of issues due to updates. I would suggest to reopen the bug, I had a similar issue as well.

**Comment by palexdev** [comment]
This seems to be a duplicate of palexdev/MFXResources#1 and my guess is the same, I believe you have some conflicts on the classpath because I'm not able to reproduce it on MaterialFX alone

My suggestion to fix this at this point is to not use MaterialFX, but rather the latest version of [MFXResources](https://github.com/palexdev/MaterialFX/tree/rewrite/modules/resources). Releases can be found here: [Maven Central](https://central.sonatype.com/artifact/io.github.palexdev/mfxresources/11.2.0/versions)

**Comment by stefanofornari** [comment]
But how can this be done? As per your comment https://github.com/palexdev/MFXResources/issues/1#issuecomment-1385532313, MaterialFX and MFXResources can not be used at the same time

**Comment by goatfanboi23** [comment]
I fixed my problem by remove the following code segment:
```
//following code scales font based on stage width
int newFont = clamp((int) (stageWidth / 40), 12, 24); 
if (n instanceof TextField field) {
    field.setFont(Font.font(newFont));
}
```

**Comment by stefanofornari** [comment]
> The latest version of MFXResources ditched the old font in favor of FontAwesome and offers its own implementation of MFXFontIcon Which means that, there should be no conflict, and you would be able to use both the old resources (from MaterialFX) and the new ones

I'll give it a try and let you know (last time I have tried there were conflicts).

**Comment by stefanofornari** [comment]
Ok, of course I understand I am using an bit of a messy combination, but I am reporting the issues anyway because real cases may be similar and the discussion may be helpful to others.

```
<dependency>
            <groupId>io.github.palexdev</groupId>
            <artifactId>materialfx</artifactId>
            <version>11.13.9</version>
</dependency>
<dependency>
            <groupId>io.github.palexdev</groupId>
            <artifactId>mfxcore</artifactId>
            <version>11.1.5</version>
</dependency>
<dependency>
            <groupId>io.github.palexdev</groupId>
            <artifactId>mfxresources</artifactId>
            <version>11.2.0</version>
</dependency>
<dependency>
            <groupId>io.github.palexdev</groupId>
            <artifactId>virtualizedfx</artifactId>
            <version>11.8.5</version>
</dependency>
```

1. MFXResources and MaterialFX may have different mapping:

```
java.lang.IllegalArgumentException: Icon description 'mfx-hyphen' is invalid!
        at io.github.palexdev.mfxresources.fonts.fontawesome.FontAwesomeSolid.lambda$toCode$0(FontAwesomeSolid.java:1457)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.github.palexdev.mfxresources.fonts.fontawesome.FontAwesomeSolid.toCode(FontAwesomeSolid.java:1457)
        at io.github.palexdev.mfxresources.fonts.MFXFontIcon.descToCode(MFXFontIcon.java:147)
        at io.github.palexdev.mfxresources.fonts.MFXFontIcon.lambda$initialize$0(MFXFontIcon.java:106)
```
2. VirtualFX still uses an old version of MFXResources:
```

Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: io/github/palexdev/mfxresources/font/MFXFontIcon
        at io.github.palexdev.virtualizedfx.controls.MFXScrollBar.createDefaultSkin(MFXScrollBar.java:140)

```

**Comment by palexdev** [comment]
@stefanofornari 
![image](https://user-images.githubusercontent.com/16880178/225629748-71c19246-a310-4689-acc9-5afcc65cfd2a.png)

Should be fixed now. Turns out the conflict was with VirtualizedFX, I updated the dependency to the latest version, and it seems to work

The only thing that leaves me perplex about your setup is having a newer version of VFX with MFX. In theory, all controls that depend on the old implementation of virtual flow should fail because the class has been moved (I'm talkina about combos, lists and such)

P.S: soon VFX 11.9.0 will be out

**Comment by palexdev** [comment]
Fixed in latest versions
