### ISSUE TITLE
Scenebuilder Raises error on opening FXML file with io.github.palexdev.mfxcomponents.controls.buttons.MFXFilledButton

### ISSUE THREAD

**Issue by infinite-dev22** [palexdev/MaterialFX#319]
java.io.IOException: javafx.fxml.LoadException: 
/home/infinite/IdeaProjects/spoty/src/main/resources/org/infinite/spoty/forms/ProductCategoryForm.fxml:24

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.handleUnknownAndMissingCauses(FXOMLoader.java:119)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.handleKnownCauses(FXOMLoader.java:126)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.handleFxmlLoadingError(FXOMLoader.java:112)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:106)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:115)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2561)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:764)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:398)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:675)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp$1.invalidated(SceneBuilderApp.java:521)
	at javafx.base@19/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@19/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@19/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@19/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@19/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at com.oracle.javafx.scenebuilder.kit.library.user.UserLibrary.lambda$updateFirstExplorationCompleted$7(UserLibrary.java:373)
	at javafx.graphics@19/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@19/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/home/infinite/IdeaProjects/spoty/src/main/resources/org/infinite/spoty/forms/ProductCategoryForm.fxml:24

	at javafx.fxml@19/javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:104)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	... 26 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "io.github.palexdev.mfxresources.MFXResources.loadURL(String)" is null
	at io.github.palexdev.mfxresources.MFXResources.load(MFXResources.java:38)
	at io.github.palexdev.mfxcomponents.controls.buttons.MFXButton.lambda$sceneBuilderIntegration$4(MFXButton.java:158)
	at io.github.palexdev.mfxcore.utils.fx.SceneBuilderIntegration.ifInSceneBuilder(SceneBuilderIntegration.java:68)
	at io.github.palexdev.mfxcomponents.controls.buttons.MFXButton.sceneBuilderIntegration(MFXButton.java:157)
	at io.github.palexdev.mfxcomponents.controls.buttons.MFXButton.initialize(MFXButton.java:125)
	at io.github.palexdev.mfxcomponents.controls.buttons.MFXButton.<init>(MFXButton.java:77)
	at io.github.palexdev.mfxcomponents.controls.buttons.MFXFilledButton.<init>(MFXFilledButton.java:44)
	at io.github.palexdev.mfxcomponents.controls.buttons.MFXFilledButton.<init>(MFXFilledButton.java:40)
	at io.github.palexdev.mfxcomponents.controls.buttons.MFXFilledButton.<init>(MFXFilledButton.java:36)
	... 29 more

**Comment by palexdev** [comment]
Ah yes, ever since the themes have been reorganized that method is broken. I already fixed it locally but I don't know how much time will take to complete the next version. I did some major changes as well as introducing new features. I need to finish the docs, re-check the old stylesheets and complete the new ones... There's a lot of work to do, I'll release asap

**Comment by palexdev** [comment]
Should have been fixed

**Comment by infinite-dev22** [comment]
The components are now available though they are kind of disturbing on my PC
MFXElevatedButton won't add.
![ezgif-1-a3e09fedaa](https://github.com/palexdev/MaterialFX/assets/77667007/18a66749-2ecf-4ed3-802f-fb4ce20f8faf)

**Comment by palexdev** [comment]
It works for me:
![image](https://github.com/palexdev/MaterialFX/assets/16880178/270ab4b4-af80-4608-9555-d75f8f0e418a)
Are you sure you are using the latest version and that nothing on the SceneBuilder classpath is interfering?

**Comment by infinite-dev22** [comment]
Let me reinstall scenebuilder and I try again

**Comment by infinite-dev22** [comment]
I also realize that you are using MFXButton and not MFXElevatedButton, could it be that in the new release MFXButton is elevated or raised by default.

**Comment by palexdev** [comment]
> I also realize that you are using MFXButton and not MFXElevatedButton, could it be that in the new release MFXButton is elevated or raised by default.

Exactly, this is why I suspect that you didn't update the library
In recent releases, I removed those extra classes. Now to change the button type you have to apply one of its Variants on it (via code)
Unfortunately, there's no feasible way to add support to this in SceneBuilder. However, you can still do it. Variants are just extra style classes that are applied on the control.
For example. Let's say you want a filled button. Start by adding MFXButton on the Scene, then go to the style class list and add "filled" (without quotes). This is the result:
![image](https://github.com/palexdev/MaterialFX/assets/16880178/8f92931a-39a7-4c86-bc64-cebd1848abd0)

This can be done with any control that has Variants (implements the WithVariants API), and of course you have to know what style class to apply, just check the source code. Variants are typically expressed with enum classes: [Enums](https://github.com/palexdev/MaterialFX/tree/rewrite/modules/components/src/main/java/io/github/palexdev/mfxcomponents/theming/enums)

**Comment by infinite-dev22** [comment]
Am loving this library more and more. lemme work on my open source contributing skills and start having contributions to it, thank you good Sir.

**Comment by infinite-dev22** [comment]
I will update my project dependancies too.
