### ISSUE TITLE
```MFXStageDialog's``` ```showAndWait()``` crushes OS.

### ISSUE THREAD

**Issue by infinite-dev22** [palexdev/MaterialFX#339]
**Describe the bug**
Calling ```MFXStageDialog's``` ```showAndWait()``` crushes the entire Operating System.

**[MRE](https://bit.ly/3k5gTJf)(Minimal Reproducible Example)**
```
public class MyAppFormController implements Initializable {
  private MFXStageDialog dialog;

  ...

  private void myAppBtnClicked() {
    myAppBtn.setOnAction(e -> dialog.showAndWait());
  }

  private void myAppDialogPane(Stage stage) throws IOException {
    FXMLLoader fxmlLoader = fxmlLoader("forms/MyAppDialogForm.fxml");
    fxmlLoader.setControllerFactory(c -> MyAppDialogFormController.getInstance());

    MFXGenericDialog dialogContent = fxmlLoader.load();

    dialogContent.setShowMinimize(false);
    dialogContent.setShowAlwaysOnTop(false);

    dialog =
        MFXGenericDialogBuilder.build(dialogContent)
            .toStageDialogBuilder()
            .initOwner(stage)
            .initModality(Modality.WINDOW_MODAL)
            .setOwnerNode(adjustmentFormContentPane)
            .setScrimPriority(ScrimPriority.WINDOW)
            .setScrimOwner(true)
            .get();

io.github.palexdev.mfxcomponents.theming.MaterialThemes.PURPLE_LIGHT.applyOn(dialog.getScene());
  }

  ...

}
```

**To Reproduce**
1. Create a ```MFXStageDialog```.
2. Show the ```MFXStageDialog``` by calling ```showAndWait()```.

**Expected behavior**
```PopUp dialog``` is shown.

**Edit: Environment(If it helps)**
![Screenshot from 2023-09-16 12-50-03](https://github.com/palexdev/MaterialFX/assets/77667007/52f2dcab-120f-4be3-a2af-899aa6bb1191)
![Screenshot from 2023-09-16 12-51-26](https://github.com/palexdev/MaterialFX/assets/77667007/48ada26d-9cff-4cf2-affe-ad67da7769d4)

**Comment by palexdev** [comment]
Can you verify it doesn't happen with a standard JavaFX Dialog and Stage?
It's hard to believe such a big issue is caused by my library, it's very strange

**Comment by infinite-dev22** [comment]
I have tested it on a standard JavaFX Dialog in the application am building, and this crashes the application and Intellij IDEA.

When I try MFXStageDialog in a new application and Stage it produces this error.
```
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: 'boolean javafx.scene.layout.Region.isFocusWithin()'
	at mfx.components@11.22.0/io.github.palexdev.mfxcomponents.controls.MaterialSurface.isOwnerFocused(MaterialSurface.java:170)
	at mfx.components@11.22.0/io.github.palexdev.mfxcomponents.controls.MaterialSurface.handleBackground(MaterialSurface.java:134)
	at mfx.components@11.22.0/io.github.palexdev.mfxcomponents.controls.MaterialSurface$1.set(MaterialSurface.java:243)
	at javafx.base@18/javafx.beans.property.DoubleProperty.setValue(DoubleProperty.java:78)
	at javafx.graphics@18/javafx.css.StyleableDoubleProperty.applyStyle(StyleableDoubleProperty.java:68)
	at javafx.graphics@18/javafx.css.StyleableDoubleProperty.applyStyle(StyleableDoubleProperty.java:45)
	at javafx.graphics@18/javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:954)
	at javafx.graphics@18/javafx.scene.Node.doProcessCSS(Node.java:9595)
	at javafx.graphics@18/javafx.scene.Node$1.doProcessCSS(Node.java:481)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSSImpl(NodeHelper.java:193)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.superProcessCSSImpl(ParentHelper.java:93)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.superProcessCSS(ParentHelper.java:63)
	at javafx.graphics@18/javafx.scene.Parent.doProcessCSS(Parent.java:1369)
	at javafx.graphics@18/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@18/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@18/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@18/javafx.scene.control.Control.doProcessCSS(Control.java:902)
	at javafx.controls@18/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls@18/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18/javafx.scene.Node.processCSS(Node.java:9477)
	at javafx.graphics@18/javafx.scene.Scene.doCSSPass(Scene.java:572)
	at javafx.graphics@18/javafx.scene.Scene.preferredSize(Scene.java:1770)
	at javafx.graphics@18/javafx.scene.Scene$2.preferredSize(Scene.java:396)
	at javafx.graphics@18/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics@18/javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics@18/javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.graphics@18/javafx.stage.Window.show(Window.java:1254)
	at javafx.graphics@18/javafx.stage.Stage.show(Stage.java:277)
	at org.infinite.test.dialogstest@1.0-SNAPSHOT/org.infinite.test.dialogstest.HelloApplication.lambda$start$1(HelloApplication.java:54)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18/javafx.scene.Node.fireEvent(Node.java:8797)
	at MaterialFX@11.16.1/io.github.palexdev.materialfx.controls.MFXToggleButton.fire(MFXToggleButton.java:132)
	at MaterialFX@11.16.1/io.github.palexdev.materialfx.controls.MFXToggleButton.lambda$setBehavior$0(MFXToggleButton.java:102)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:221)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3586)
	at javafx.graphics@18/javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
	at javafx.graphics@18/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@18/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: 'boolean javafx.scene.layout.Region.isFocusWithin()'
	at mfx.components@11.22.0/io.github.palexdev.mfxcomponents.controls.MaterialSurface.isOwnerFocused(MaterialSurface.java:170)
	at mfx.components@11.22.0/io.github.palexdev.mfxcomponents.controls.MaterialSurface.handleBackground(MaterialSurface.java:134)
	at mfx.components@11.22.0/io.github.palexdev.mfxcomponents.controls.MaterialSurface$1.set(MaterialSurface.java:243)
	at javafx.base@18/javafx.beans.property.DoubleProperty.setValue(DoubleProperty.java:78)
	at javafx.graphics@18/javafx.css.StyleableDoubleProperty.applyStyle(StyleableDoubleProperty.java:68)
	at javafx.graphics@18/javafx.css.StyleableDoubleProperty.applyStyle(StyleableDoubleProperty.java:45)
	at javafx.graphics@18/javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:954)
	at javafx.graphics@18/javafx.scene.Node.doProcessCSS(Node.java:9595)
	at javafx.graphics@18/javafx.scene.Node$1.doProcessCSS(Node.java:481)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSSImpl(NodeHelper.java:193)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.superProcessCSSImpl(ParentHelper.java:93)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.superProcessCSS(ParentHelper.java:63)
	at javafx.graphics@18/javafx.scene.Parent.doProcessCSS(Parent.java:1369)
	at javafx.graphics@18/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@18/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@18/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@18/javafx.scene.control.Control.doProcessCSS(Control.java:902)
	at javafx.controls@18/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls@18/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18/javafx.scene.Node.processCSS(Node.java:9477)
	at javafx.graphics@18/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18/javafx.scene.Scene.doCSSPass(Scene.java:572)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2494)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:405)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:404)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:434)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by palexdev** [comment]
Gradle or Maven, may I ask what are the project's dependencies?

**Comment by infinite-dev22** [comment]
Am using gradle.
```
dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.43.0.0'
    implementation 'com.j256.ormlite:ormlite-jdbc:6.1'
    implementation 'org.jetbrains:annotations:24.0.1'
    implementation 'io.github.palexdev:materialfx:11.16.1'
    implementation('org.kordamp.ikonli:ikonli-javafx:12.3.1')
    implementation "org.kordamp.ikonli:ikonli-core:12.3.1"
    implementation "org.kordamp.ikonli:ikonli-fontawesome5-pack:12.3.1"
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    implementation 'jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.1'
    implementation "fr.brouillard.oss:cssfx:11.5.1"
    implementation "io.github.palexdev:scenicview:17.0.2"
    implementation "io.github.palexdev:virtualizedfx:11.9.6"
    implementation "io.github.palexdev:mfxcomponents:11.22.0"
    implementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    implementation "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
}
```

**Comment by palexdev** [comment]
Ok, the issue is that one of your dependencies is probably forcing the use of an older version of JavaFX
In fact, if you check the logs, you can see this `javafx.controls@18`, which means you are using JavaFX 18
MaterialFX requires the latest version available since the `focusVisible` and `focusWithin` features have been implemented only recently

**Comment by infinite-dev22** [comment]
Thanks, this fixes the Sample App I had created to verify below.

> Can you verify it doesn't happen with a standard JavaFX Dialog and Stage? It's hard to believe such a big issue is caused by my library, it's very strange.

Though now the actual app I am building in which the dialog crashes the system still does so. I can't get its error stack as the ```OS``` crashes. Is there a way you advise Sir that I can get the error stack.

**Comment by palexdev** [comment]
Maybe try on another OS or PC
It's very strange

**Comment by infinite-dev22** [comment]
It's the app, I confirm with the Sample App, there the dialog works well though now on my program it does crash. Previously I wasn't facing the issue though, started acting of recent when I resumed work on my program.

**Comment by palexdev** [comment]
Did you solve it?

**Comment by infinite-dev22** [comment]
Not yet, Sir. Let me try to look into the thread creation and execution in the program more, I think that's where the problem is.

**Comment by infinite-dev22** [comment]
Still failed to fix this in my App, guess I could share with you my repo so You can take a look at it.
**Note:** It's not a framework issue, I think it's with how I wrote my code.

**Comment by palexdev** [comment]
The MRE you posted is enough to reproduce the issue?
Since that is in a controller did you just copy it from your app? If that's the case I will need a MRE that doesn't have any other code around, just the bare minimum to reproduce the issue

**Comment by infinite-dev22** [comment]
> The MRE you posted is enough to reproduce the issue? Since that is in a controller did you just copy it from your app? If that's the case I will need a MRE that doesn't have any other code around, just the bare minimum to reproduce the issue

An MRE doesn't seem to have the bug, it's within my app.

**Comment by palexdev** [comment]
Then I don't think I can help you with that
It could be anything, hardware, OS, JDK. A crash without exceptions or traces is so strange, you are surely doing something sketchy somewhere, just keep finding
In such cases, it may also be a good idea to restart or comment all the code and reintroduce functionalities little by little, while starting the app. This way you can find the snipped it's causing it

**Comment by infinite-dev22** [comment]
The app was working fine previously, I put a hold on its development as I had some errands to run and on resuming development a month later, I get this error. Thanks for your time though, I will do as you said, Introduce functionalities little by little.

**Comment by palexdev** [comment]
See, this is a good place to start. In one month did you update the OS or made other software changes? Changed JDK? Ubuntu can be a quite troublesome distro, I know for a fact

**Comment by palexdev** [comment]
Anyway, if you want further confirmation, I can try running your app on my PC and see what happens

**Comment by infinite-dev22** [comment]
> See, this is a good place to start. In one month did you update the OS or made other software changes? Changed JDK? Ubuntu can be a quite troublesome distro, I know for a fact

I did update, but now I reinstalled with hope this would be fixed. I did as you had told me to:
> Then I don't think I can help you with that It could be anything, hardware, OS, JDK. A crash without exceptions or traces is so strange, you are surely doing something sketchy somewhere, just keep finding In such cases, it may also be a good idea to restart or comment all the code and reintroduce functionalities little by little, while starting the app. This way you can find the snippet that is causing it

I rolled back my commits and merges to previous and issue still persists. I now confirm this is Operating System specific(Issue is with the Operating System).

> Anyway, if you want further confirmation, I can try running your app on my PC and see what happens
Thank you sir, should I send an Installer or share my repository(sent you an invitation, Sir).

**Comment by palexdev** [comment]
Let me try with an installer first, just to see if it runs or crashes
If it's the latter then I may need to check the source code

**Comment by infinite-dev22** [comment]
I shall share this through email. the file(~71MB) exceeds the maximum size(25MB) accepted here

**Comment by palexdev** [comment]
Ok, you'll have to wait for tomorrow though when I'll have a good internet connection to set up an Ubuntu VM

**Comment by infinite-dev22** [comment]
I now think the problem is with my computer. I have reinstalled my OS multiple times and now even switched Distros and the same still happens yets when the app is run on another computer, it works fine.

**Comment by palexdev** [comment]
> I now think the problem is with my computer. I have reinstalled my OS(Ubuntu 22.04, 23.04, 23.10) multiple times and now even switched Distros(Garuda Linux) and the same still happens yet when the app is run on another computer, it works fine.

Already tried reintroducing features little by little? There must be something your PC doesn't like

**Comment by infinite-dev22** [comment]
I was advised by my technician that it might be a problem with my storage, so I have bought an SSD to try out again. Am sure it will work else I will switch to Windows and build from there

**Comment by infinite-dev22** [comment]
Update on this, The app still crashes on my PC but runs well and smooth in a virtual machine

**Comment by infinite-dev22** [comment]
I did get this Gnome session log.
```
18:40:00 nautilus: Could not delete '.meta.isrunning': No such file or directory
18:39:53 gnome-shell: DING: GNOME nautilus 42.6
18:39:53 gnome-shell: DING: GNOME nautilus 42.6
18:39:53 gnome-shell: DING: Detected async api for thumbnails
18:39:53 dbus-daemon: [session uid=1000 pid=1245] Successfully activated service 'org.gnome.ArchiveManager1'
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x56243fd88a30] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x56243fd88a30] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x56243fd84b10] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x56243fd886b0] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x56243fd84720] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x56243e3f2330] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x56243fd88a30] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x56243fd84b10] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x56243fd886b0] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x56243fd84720] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x56243e3f2330] is on because it needs an allocation.
18:39:52 gnome-shell: Registering session with GDM
18:39:52 gnome-shell: GNOME Shell started at Mon Sep 25 2023 18:39:48 GMT-0400 (EDT)
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x56243fd886b0] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x56243fd84720] is on because it needs an allocation.
18:39:52 gnome-shell: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x56243e3f2330] is on because it needs an allocation.
18:39:50 dbus-daemon: [session uid=1000 pid=1245] Successfully activated service 'org.freedesktop.FileManager1'
18:39:50 gnome-shell: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
18:39:50 gsd-media-keys: Failed to grab accelerator for keybinding settings:rotate-video-lock
18:39:49 gsd-color: unable to get EDID for xrandr-Virtual-1: unable to get EDID for output
18:39:49 systemd: Started GNOME Shell on X11.
18:39:49 dbus-daemon: [session uid=1000 pid=1245] Successfully activated service 'org.gnome.Shell.Notifications'
18:39:48 gnome-shell: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
18:39:48 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:48 gnome-shell: Will monitor session 2
18:39:47 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:47 gnome-shell: Xlib:  extension "DPMS" missing on display ":0".
18:39:46 systemd: Starting GNOME Shell on X11...
18:39:46 gnome-shell: shmget failed
18:39:44 gsd-media-keys: Failed to grab accelerator for keybinding settings:hibernate
18:39:44 gnome-shell: Getting layout failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.143 was not provided by any .service files
18:39:44 gsd-color: unable to get EDID for xrandr-Virtual-1: unable to get EDID for output
18:39:43 systemd: Started GNOME Shell on X11.
18:39:43 dbus-daemon: [session uid=1000 pid=1245] Successfully activated service 'org.gnome.Shell.Notifications'
18:39:43 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:42 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:41 gnome-shell: ATK Bridge is disabled but a11y has already been enabled.
18:39:41 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:41 gnome-shell: Xlib:  extension "DPMS" missing on display ":0".
18:39:40 systemd: Starting GNOME Shell on X11...
18:39:40 gnome-shell: shmget failed
18:39:38 gsd-media-keys: Failed to grab accelerator for keybinding settings:playback-random
18:39:38 gsd-color: unable to get EDID for xrandr-Virtual-1: unable to get EDID for output
18:39:37 systemd: Started GNOME Shell on X11.
18:39:37 dbus-daemon: [session uid=1000 pid=1245] Successfully activated service 'org.gnome.Shell.Notifications'
18:39:37 gnome-shell: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
18:39:36 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:36 gnome-shell: Will monitor session 2
18:39:35 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:35 gnome-shell: Xlib:  extension "DPMS" missing on display ":0".
18:39:35 systemd: Starting GNOME Shell on X11...
18:39:35 gnome-shell: shmget failed
18:39:33 dbus-daemon: [session uid=1000 pid=1245] Successfully activated service 'org.freedesktop.FileManager1'
18:39:33 gnome-shell: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
18:39:32 gsd-media-keys: Failed to grab accelerator for keybinding settings:rotate-video-lock
18:39:32 gsd-color: unable to get EDID for xrandr-Virtual-1: unable to get EDID for output
18:39:31 systemd: Started GNOME Shell on X11.
18:39:31 dbus-daemon: [session uid=1000 pid=1245] Successfully activated service 'org.gnome.Shell.Notifications'
18:39:31 gnome-shell: Telepathy is not available, chat integration will be disabled.
18:39:30 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:30 gnome-shell: Will monitor session 2
18:39:29 gsd-media-keys: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Shell”
18:39:29 gnome-shell: Xlib:  extension "DPMS" missing on display ":0".
18:39:27 systemd: Starting GNOME Shell on X11...
18:39:26 gnome-shell: shmget failed
```
The above pattern is seen whenever the application crashes.
