### ISSUE TITLE
MFXPasswordField's getMFXContextMenu() returns null

### ISSUE THREAD

**Issue by DocJohnWatson** [palexdev/MaterialFX#69]
I'm trying to change the style of MFXPasswordField's MFXContectMenu using CSS but the method getMFXContextMenu() returns null, also I can't create a new MFXContectMenu and use it instead because setMFXContextMenu() seems to not work, maybe something with the control's Skin? MFXTextFieldField's methods work.

Thanks in advance, nice library :)

**Comment by palexdev** [comment]
Can you share a minimal reproducible example please?

**Comment by DocJohnWatson** [comment]
My LoginController :

```java
package gui.login;

import io.github.palexdev.materialfx.controls.MFXButton;
import io.github.palexdev.materialfx.controls.MFXPasswordField;
import io.github.palexdev.materialfx.controls.MFXTextField;
import javafx.fxml.FXML;
import javafx.scene.text.Text;

public class LoginController {

    private LoginModel loginModel;
    private LoginService loginService;
    @FXML
    private Text applicationNameText;
    @FXML
    private MFXTextField usernameField;
    @FXML
    private MFXPasswordField passwordField;
    @FXML
    private MFXButton loginButton;

    @FXML
    private void initialize() {
        loginModel = new LoginModel();
        loginService = new LoginService();
        applicationNameText.setText("My App");
        usernameField.textProperty().bindBidirectional(loginModel.usernameProperty());
        passwordField.passwordProperty().bindBidirectional(loginModel.passwordProperty());
        loginButton.setOnAction(actionEvent -> loginButtonAction());
        setFieldsContextMenuStyle();
    }

    private void loginButtonAction() {
        //TODO
        if (loginService.login(loginModel)) {

        } else {

        }
    }

    private void setFieldsContextMenuStyle() {
        usernameField.getMFXContextMenu().getStylesheets().add("/gui/context/context-style.css");
        usernameField.getMFXContextMenu().setStyle("-fx-background-color: #fafafb; -fx-border-color: #eaeaea");
        passwordField.getMFXContextMenu().getStylesheets().add("/gui/context/context-style.css");
        passwordField.getMFXContextMenu().setStyle("-fx-background-color: #fafafb; -fx-border-color: #eaeaea");
        passwordField.setIcon(null);
    }

}
```

My FXML :

```XML
<?xml version="1.0" encoding="UTF-8"?>

<?import io.github.palexdev.materialfx.controls.MFXButton?>
<?import io.github.palexdev.materialfx.controls.MFXPasswordField?>
<?import io.github.palexdev.materialfx.controls.MFXTextField?>
<?import javafx.geometry.Insets?>
<?import javafx.scene.control.ScrollPane?>
<?import javafx.scene.layout.ColumnConstraints?>
<?import javafx.scene.layout.GridPane?>
<?import javafx.scene.layout.RowConstraints?>
<?import javafx.scene.layout.VBox?>
<?import javafx.scene.text.Text?>
<?import javafx.scene.text.TextFlow?>

<GridPane fx:id="rootGridPane" prefHeight="500.0" prefWidth="700.0" stylesheets="@login-style.css" xmlns="http://javafx.com/javafx/16" xmlns:fx="http://javafx.com/fxml/1" fx:controller="gui.login.LoginController">
   <columnConstraints>
      <ColumnConstraints hgrow="SOMETIMES" />
   </columnConstraints>
   <rowConstraints>
      <RowConstraints vgrow="SOMETIMES" />
   </rowConstraints>
   <children>
      <ScrollPane fx:id="loginFormScrollPane" styleClass="edge-to-edge">
         <content>
            <VBox fx:id="loginFormVBox" alignment="CENTER">
               <children>
                  <TextFlow fx:id="applicationNameTextFlow">
                     <children>
                        <Text fx:id="applicationNameText" strokeType="OUTSIDE" strokeWidth="0.0" />
                     </children>
                     <VBox.margin>
                        <Insets bottom="35.0" left="20.0" right="20.0" />
                     </VBox.margin>
                  </TextFlow>
                  <MFXTextField fx:id="usernameField" promptText="%field.prompt.username">
                     <VBox.margin>
                        <Insets bottom="10.0" left="20.0" right="20.0" />
                     </VBox.margin>
                  </MFXTextField>
                  <MFXPasswordField fx:id="passwordField" promptText="%field.prompt.password">
                     <VBox.margin>
                        <Insets bottom="35.0" left="20.0" right="20.0" />
                     </VBox.margin>
                  </MFXPasswordField>
                  <MFXButton fx:id="loginButton" mnemonicParsing="false" rippleAnimateShadow="true" text="%button.login">
                     <VBox.margin>
                        <Insets bottom="50.0" left="20.0" right="20.0" />
                     </VBox.margin>
                  </MFXButton>
               </children>
            </VBox>
         </content>
      </ScrollPane>
   </children>
</GridPane>
```

If I comment the 3rd and 4th line in the method "setFieldsContextMenuStyle()" it runs, otherwise it throws an exception.


```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javafx.fxml.LoadException: 
/C:/Users/Dr_John_Watson/IdeaProjects/MaterialFXContext/target/classes/gui/login/login-view.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2677)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2517)
	at App.loadFXML(App.java:26)
	at App.start(App.java:18)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2673)
	... 13 more
Caused by: java.lang.NullPointerException
	at gui.login.LoginController.setFieldsContextMenuStyle(LoginController.java:45)
	at gui.login.LoginController.initialize(LoginController.java:30)
	... 25 more

Process finished with exit code 1
```

I also attached the project, in case it is needed.
[MaterialFXContext.zip](https://github.com/palexdev/MaterialFX/files/6801405/MaterialFXContext.zip)

**Comment by palexdev** [comment]
Thanks for the quick response
Soon I'm going to release the new version

**Comment by palexdev** [comment]
@DocJohnWatson is this what you are trying to achieve?
![image](https://user-images.githubusercontent.com/16880178/125349866-58bacc00-e35e-11eb-89c6-ec47accf3a1c.png)

**Comment by DocJohnWatson** [comment]
Yes, exactly. 😄 @palexdev

**Comment by palexdev** [comment]
Fixed, new version coming soon 😉
